### ISSUE TITLE
Unable to create case due to no HCPCS Drop down on case screen for rendering provider

### ISSUE THREAD

**Issue by zunich** [ppazos/amplify-prototype#35]
Google Chrome is up to date
Version 71.0.3578.98 (Official Build) (64-bit)

I cannot select a service provided by the rendering provider due to the HCPCS drop down box not showing available services. 

See screenshot

![screen shot 2019-01-25 at 11 56 58 am 2](https://user-images.githubusercontent.com/17009855/51763548-7dd8f880-2098-11e9-841b-46a026e28a42.png)

**Comment by ppazos** [comment]
Fixed, the issue was due a log configuration I use for testing was breaking the JSON responses from the server, I need to remember to furn that off when the app is deployed. @zunich
